kmod/sof_remove: show systemctl units when pulseaudio is running
When pulseaudio is running display not just the warning but this too:

skipping snd_compress, not loaded
skipping snd_pcm, not loaded
553 /usr/bin/pulseaudio --daemonize=no --log-target=journal
ERROR: sof_remove.sh fails semi-randomly when pulseaudio is running
  UNIT               LOAD   ACTIVE   SUB     DESCRIPTION
  pulseaudio.service loaded active   running Sound Service
  pulseaudio.socket  masked inactive dead    pulseaudio.socket

This points the user towards a root-cause.

Also remove obsolete `builtin exit`

Signed-off-by: Marc Herbert <marc.herbert@intel.com>