New systemctl_show_pulseaudio() that catches the sneaky 'gdm' user
Trying to stop the unstoppable thanks to the --global option

Sample ~/SOF/sof-test/tools/kmod/sof_remove.sh output:

SKIP	snd_compress  	not loaded
SKIP	snd_pcm  	not loaded
529 /usr/bin/pulseaudio --daemonize=no --log-target=journal

+ systemctl --system list-unit-files --all '*pulse*'
UNIT FILE                           STATE  VENDOR PRESET
pulseaudio-enable-autospawn.service masked enabled

1 unit files listed.

+ systemctl --global list-unit-files --all '*pulse*'
UNIT FILE          STATE   VENDOR PRESET
pulseaudio.service enabled enabled
pulseaudio.socket  enabled enabled

2 unit files listed.

+ systemctl --user list-unit-files --all '*pulse*'
UNIT FILE          STATE  VENDOR PRESET
pulseaudio.service masked enabled
pulseaudio.socket  masked enabled

2 unit files listed.

For joe ONLY:
+ systemctl --user list-units --all '*pulse*'
  UNIT               LOAD   ACTIVE   SUB  DESCRIPTION
● pulseaudio.service masked inactive dead pulseaudio.service
● pulseaudio.socket  masked inactive dead pulseaudio.socket

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
gdm          529  0.0  0.3 804512 13960 ?        S<sl 13:46   0:00 /usr/bin/pulseaudio --daemonize=no --log-target=journal

ERROR: sof_remove.sh fails semi-randomly when pulseaudio is running

Try: sudo systemctl --global mask pulseaudio.{socket,service} and reboot.
    --global is required for session managers like "gdm"

Signed-off-by: Marc Herbert <marc.herbert@intel.com>