lib.sh: catch some mtrace-reader failures to start thanks to "OSError"
This makes tests fail at the end when mtrace-reader.py could be started,
for instance because one is already running (see example below)

Reminder: you can use -s to ignore firmware logs.

Traceback (most recent call last):
  File "mtrace-reader.py", line 20, in <module>
    fd = os.open(MTRACE_FILE, os.O_RDONLY)
OSError: [Errno 16] Device or resource busy: '/sys/kernel/debug/sof/mtrace/core0'

Signed-off-by: Marc Herbert <marc.herbert@intel.com>