lib.sh: fix etrace collection on failure (recent regression)
Fixes failures to collect etrace on failure. It goes like this:

UTC [INFO] Starting sof-logger '' -l /lib/firmware/intel/sof/sof-apl.ldc
 -o sof-test/logs/check-runtime-pm-status/2021-12-02-23:49:42-22493/etrace.txt
error: Unused parameter ''
Usage sof-logger <option(s)> <file(s)>

This happens when $logopt is empty.

Fixes recent regression introduced by commit 814b904acfca6 ("lib.sh: fix
sudo "$loggerCmd" quoting")

Signed-off-by: Marc Herbert <marc.herbert@intel.com>