fake_kern_error: add missing \n when writing to /dev/kmsg
This wasn't really a problem as long as sof-kernel-log-check.sh was
reading /var/log/kernel.log, which just changed in PR #529

Signed-off-by: Marc Herbert <marc.herbert@intel.com>