sof_remove: unload `snd_sof_intel_hda_common` before `soundwire_intel`
Fixes this failure with older kernel like the 6.5 kernels distributed by
Ubuntu:

 ERROR: Module soundwire_intel is in use by: snd_sof_intel_hda_common

Fixes commit 65951c4d0 ("kmod: fix hda-sdw-bpt dependency") which
unloaded all soundwire drivers earlier as a block. This is not a problem
with 6.9-ish kernels where snd_sof_intel_hda_common and soundwire_intel
can apparently be unloaded in any order but it is a problem with older
kernels.

So, unload `snd_sof_intel_hda_common` before soundwire modules to be
compatible with any kernel.

See https://github.com/thesofproject/sof-test/pull/1156 for more info.